<?php
/**
 * @var \Zend\View\Helper\Navigation\Menu $menu
 * @var Zend\Navigation\Page\Mvc          $page
 */
$menu = $this->navigation()->menu();
?>
<ul class="<?= $menu->getUlClass() ?>" id="horizontal-nav">
    <?php foreach ($this->container as $page): ?>
        <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <li class="<?= $page->getActive(true) ? 'active' : null; ?>">
            <a href="<?= $page->getHref(); ?>"><?= $this->translate($page->getLabel()); ?></a>
        </li>
    <?php endforeach ?>
</ul>
