language: php

php:
  - 5.5

before_script:
  - composer self-update
  - composer install --dev

script:
  - mkdir -p build/logs
  - phpunit --configuration test/phpunit.xml
  - phpunit --testdox --coverage-clover build/logs/clover.xml --configuration test/phpunit.xml

after_script:
 - php vendor/bin/coveralls -v