language: php

php:
  - 5.5

before_script:
  - composer self-update
  - composer install --dev

script:
  - mkdir -p build/logs
  - cd test
  - phpunit

after_script:
 - cd ..
 - php vendor/bin/coveralls -v