<?php

return [
    'ApplicationFeatureLibraryBooks\Module' => __DIR__ . '/Module.php',
    'ApplicationFeatureLibraryBooks\Controller\CreateController' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Controller/CreateController.php',
    'ApplicationFeatureLibraryBooks\Controller\DeleteController' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Controller/DeleteController.php',
    'ApplicationFeatureLibraryBooks\Controller\IndexController' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Controller/IndexController.php',
    'ApplicationFeatureLibraryBooks\Controller\ReadController' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Controller/ReadController.php',
    'ApplicationFeatureLibraryBooks\Controller\UpdateController' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Controller/UpdateController.php',
    'ApplicationFeatureLibraryBooks\Controller\SLFactory\CreateControllerSLFactory' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Controller/SLFactory/CreateControllerSLFactory.php',
    'ApplicationFeatureLibraryBooks\Controller\SLFactory\DeleteControllerSLFactory' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Controller/SLFactory/DeleteControllerSLFactory.php',
    'ApplicationFeatureLibraryBooks\Controller\SLFactory\IndexControllerSLFactory' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Controller/SLFactory/IndexControllerSLFactory.php',
    'ApplicationFeatureLibraryBooks\Controller\SLFactory\ReadControllerSLFactory' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Controller/SLFactory/ReadControllerSLFactory.php',
    'ApplicationFeatureLibraryBooks\Controller\SLFactory\UpdateControllerSLFactory' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Controller/SLFactory/UpdateControllerSLFactory.php',
    'ApplicationFeatureLibraryBooks\Form\CreateForm' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Form/CreateForm.php',
    'ApplicationFeatureLibraryBooks\Form\CreateFormInputFilter' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Form/CreateFormInputFilter.php',
    'ApplicationFeatureLibraryBooks\Form\DeleteForm' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Form/DeleteForm.php',
    'ApplicationFeatureLibraryBooks\Form\DeleteFormInputFilter' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Form/DeleteFormInputFilter.php',
    'ApplicationFeatureLibraryBooks\Form\SLFactory\CreateFormSLFactory' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Form/SLFactory/CreateFormSLFactory.php',
    'ApplicationFeatureLibraryBooks\Form\SLFactory\DeleteFormSLFactory' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Form/SLFactory/DeleteFormSLFactory.php',
    'ApplicationFeatureLibraryBooks\Service\CrudService' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Service/CrudService.php',
    'ApplicationFeatureLibraryBooks\Service\FilterResultsService' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Service/FilterResultsService.php',
    'ApplicationFeatureLibraryBooks\Service\SLFactory\CrudServiceSLFactory' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Service/SLFactory/CrudServiceSLFactory.php',
    'ApplicationFeatureLibraryBooks\Service\SLFactory\FilterResultsServiceSLFactory' => __DIR__ . '/src/ApplicationFeatureLibraryBooks/Service/SLFactory/FilterResultsServiceSLFactory.php',
];
