<?php

return [
    'Module\LibraryBooks\Module' => __DIR__ . '/Module.php',
    'Module\LibraryBooks\Controller\CreateController' => __DIR__ . '/src/LibraryBooks/Controller/CreateController.php',
    'Module\LibraryBooks\Controller\DeleteController' => __DIR__ . '/src/LibraryBooks/Controller/DeleteController.php',
    'Module\LibraryBooks\Controller\IndexController' => __DIR__ . '/src/LibraryBooks/Controller/IndexController.php',
    'Module\LibraryBooks\Controller\ReadController' => __DIR__ . '/src/LibraryBooks/Controller/ReadController.php',
    'Module\LibraryBooks\Controller\UpdateController' => __DIR__ . '/src/LibraryBooks/Controller/UpdateController.php',
    'Module\LibraryBooks\Controller\SLFactory\CreateControllerSLFactory' => __DIR__ . '/src/LibraryBooks/Controller/SLFactory/CreateControllerSLFactory.php',
    'Module\LibraryBooks\Controller\SLFactory\DeleteControllerSLFactory' => __DIR__ . '/src/LibraryBooks/Controller/SLFactory/DeleteControllerSLFactory.php',
    'Module\LibraryBooks\Controller\SLFactory\IndexControllerSLFactory' => __DIR__ . '/src/LibraryBooks/Controller/SLFactory/IndexControllerSLFactory.php',
    'Module\LibraryBooks\Controller\SLFactory\ReadControllerSLFactory' => __DIR__ . '/src/LibraryBooks/Controller/SLFactory/ReadControllerSLFactory.php',
    'Module\LibraryBooks\Controller\SLFactory\UpdateControllerSLFactory' => __DIR__ . '/src/LibraryBooks/Controller/SLFactory/UpdateControllerSLFactory.php',
    'Module\LibraryBooks\Form\CreateForm' => __DIR__ . '/src/LibraryBooks/Form/CreateForm.php',
    'Module\LibraryBooks\Form\CreateFormInputFilter' => __DIR__ . '/src/LibraryBooks/Form/CreateFormInputFilter.php',
    'Module\LibraryBooks\Form\DeleteForm' => __DIR__ . '/src/LibraryBooks/Form/DeleteForm.php',
    'Module\LibraryBooks\Form\DeleteFormInputFilter' => __DIR__ . '/src/LibraryBooks/Form/DeleteFormInputFilter.php',
    'Module\LibraryBooks\Form\SLFactory\CreateFormSLFactory' => __DIR__ . '/src/LibraryBooks/Form/SLFactory/CreateFormSLFactory.php',
    'Module\LibraryBooks\Form\SLFactory\DeleteFormSLFactory' => __DIR__ . '/src/LibraryBooks/Form/SLFactory/DeleteFormSLFactory.php',
    'Module\LibraryBooks\Service\CrudService' => __DIR__ . '/src/LibraryBooks/Service/CrudService.php',
    'Module\LibraryBooks\Service\FilterResultsService' => __DIR__ . '/src/LibraryBooks/Service/FilterResultsService.php',
    'Module\LibraryBooks\Service\SLFactory\CrudServiceSLFactory' => __DIR__ . '/src/LibraryBooks/Service/SLFactory/CrudServiceSLFactory.php',
    'Module\LibraryBooks\Service\SLFactory\FilterResultsServiceSLFactory' => __DIR__ . '/src/LibraryBooks/Service/SLFactory/FilterResultsServiceSLFactory.php',
];
