<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 Adv. demo')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- styles -->
    <?php echo $this->headLink(
        [
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ]
    )
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                <img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="ZF2 Demo"/>
                &nbsp;<?php echo $this->translate('Demo') ?>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <?= $this->partial('partial/top-menu'); ?>
            <ul class="nav navbar-nav navbar-right">
            <?php /** @var \BusinessLogic\Users\Entity\UserEntity $identity */ ?>
            <?php if (($identity = $this->identity())): ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-user"></span>
                        <?= $identity->getName(); ?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Edit profile</a></li>
                        <li class="divider"></li>
                        <li><a href="<?= $this->url('auth/default', ['controller' => 'logout']); ?>">
                            <span class="glyphicon glyphicon-off"></span> Logout
                            </a>
                        </li>
                    </ul>
                </li>
            <?php else: ?>
                <li><a href="<?= $this->url('auth/default', ['controller' => 'login']); ?>">Login</a></li>
            <?php endif; ?>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <?= $this->partial('partial/messages') ?>
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; 2014 by Rafal Ksiazek</p>
    </footer>
</div>
<?php echo $this->inlineScript() ?>
</body>
</html>
